### ISSUE TITLE
Incompatible major interface version. Expected 0, got 1

### ISSUE THREAD

**Issue by StebanDev** [dshoreman/albert-translate#4]
Hi, I'm on Manjaro and after following the installation instructions I see in the albert settings ui that the plugin appears disabled, then I started from the console to see the logs and I got the following error:

`17:51:25 [debg:python.modulev1] Reading metadata of python module: translate
17:51:25 [warn:python.modulev1] [translate] Incompatible major interface version. Expected 0, got 1`

By the way, I have the built-in translate plugin disabled. I would really appreciate your help as I have frequently issues with the rate limit on native plugin.

**Comment by dshoreman** [comment]
This could be due to recent changes to the plugin API in albert, which IIRC got a big refactor not too long ago. Are you able to try with an older version of Albert to see if that works?

**Comment by dshoreman** [comment]
Closing; see https://github.com/dshoreman/albert-translate/pull/5#issuecomment-955640945 for details.
